export const DEFAULT_LLM = 'claude-sonnet-4-6'
export const COMPANY_CLEANUP_TABLE = 'mockTestUsers'
export const COMPANY_CLEANUP_THRESHOLD_DAYS = '30'
export const DEFAULT_CRONJOB_TIME = '0 17 * * *'
export const DEFAULT_CRONJOB_TIMEZONE = 'Australia/Sydney'
